# https://github.com/johnthagen/min-sized-rust

# [build]
# rustflags = ["--cfg", "tokio_unstable"]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = "debuginfo"

# [registries.crates-io]
# protocol = "sparse"
